### ISSUE TITLE
Unable to install updated apk

### ISSUE THREAD

**Issue by feerlessleadr** [Jaxel/TheDonald.win#2]
Hi, I just attempted to install the latest app release (released today), and a pop-up shows up from play protect saying that the apps developer isn't recognized (never seen that before on any side loaded app).

![Screenshot_20201208-140315_Google Play Store](https://user-images.githubusercontent.com/288895/101529158-32632700-395e-11eb-8edb-54290f5a2bbd.jpg)

I click install anyway, but then it tells me the app isn't installed. 

![Screenshot_20201208-140321_Package installer](https://user-images.githubusercontent.com/288895/101529168-3a22cb80-395e-11eb-85fb-ef8dfa555466.jpg)

Not sure if this is something I'm doing wrong or a bug. Please let me know if you need some sort of log to debug. I'm running Android 10 on a galaxy s9.

The good news is I can still use the app, so I'm hesitant to uninstall and install fresh in case it does the same thing.

**Comment by tommytom02** [comment]
Remove old app first and disable play protect. Worked for me on my VZW LG V30 running Pie

**Comment by aburke20** [comment]
Same, just delete old one, and then install new.

**Comment by feerlessleadr** [comment]
perfect - I figured that might do it, but didn't want to mess up a working app in case it was something else. Thanks all!

**Comment by Jaxel** [comment]
Yeah. I am on a new computer, and I don't have the encryption keys I used on the previous releases. So I had to create new keys; which technically makes it a new program; so it won't overwrite the old program, for security reasons. Google does it this way because otherwise someone who is not the original app author could create a "fake" version of an app and install it over your original. This way it prevents app overwrites from anyone except the original encryption keys.
